services:
  mysql:
    image: mysql:8.0
    container_name: customs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: customs_clearance
      MYSQL_USER: customs_user
      MYSQL_PASSWORD: customs_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - customs-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: customs-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: customs_user
      PMA_PASSWORD: customs_pass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - customs-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: customs-chromadb
    restart: unless-stopped
    env_file:
      - ./chromadb/.env
    ports:
      - "8011:8000"
    volumes:
      # 데이터 바인드 마운트
      - ./chromadb/data/chroma_db:/data
      # 설정 및 스크립트 마운트
      - ./chromadb/scripts:/scripts:ro
    networks:
      - customs-network

  # 챗봇 전용 PostgreSQL (대화기록 저장소)
  chatbot-postgres:
    image: postgres:15-alpine
    container_name: customs-chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: conversations
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=ko_KR.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - chatbot_postgres_data:/var/lib/postgresql/data
      - ./chatbot/postgres/init:/docker-entrypoint-initdb.d
    command: >
      postgres -c log_statement=all
               -c log_min_duration_statement=0
               -c shared_preload_libraries=pg_stat_statements
               -c max_connections=200
               -c shared_buffers=256MB
               -c effective_cache_size=512MB
    networks:
      - customs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d conversations"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 챗봇 전용 Redis (캐시 및 세션 저장소)
  chatbot-redis:
    image: redis:7-alpine
    container_name: customs-chatbot-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - chatbot_redis_data:/data
      - ./chatbot/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - customs-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # pgAdmin (PostgreSQL 웹 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: customs-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@customs-clearance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - chatbot-postgres
    networks:
      - customs-network
    profiles: ["with-pgadmin"]

volumes:
  mysql_data:
  chatbot_postgres_data:
  chatbot_redis_data:
  pgadmin_data:

networks:
  customs-network:
    driver: bridge