services:
  mysql:
    image: mysql:8.0
    container_name: customs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: customs_clearance
      MYSQL_USER: customs_user
      MYSQL_PASSWORD: customs_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - customs-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: customs-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: customs_user
      PMA_PASSWORD: customs_pass
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - customs-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: customs-chromadb
    restart: unless-stopped
    env_file:
      - ./chromadb/.env
    ports:
      - "8011:8000"
    volumes:
      # 데이터 바인드 마운트
      - ./chromadb/data/chroma_db:/data
      # 설정 및 스크립트 마운트
      - ./chromadb/scripts:/scripts:ro
    networks:
      - customs-network

volumes:
  mysql_data:

networks:
  customs-network:
    driver: bridge