apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hscode-us-convert
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
      - name: hscode-us-convert-container
        image: asia-northeast3-docker.pkg.dev/customs-clearance-system/docker-repo/hscode-us-converter:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: SERVICE_NAME
          value: "US-Korea HS Code Converter Service"
        - name: UV_SYSTEM_PYTHON
          value: "1"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENABLE_DOCS
          value: "true"
        - name: PYTHONPATH
          value: "/app"
        - name: US_TARIFF_FILE
          value: "/app/us_tariff_table_20250714.xlsx"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: openai-api-key
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true