apiVersion: apps/v1
kind: Deployment
metadata:
  name: hscode-us-convert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hscode-us-convert
  template:
    metadata:
      labels:
        app: hscode-us-convert
    spec:
      containers:
      - name: hscode-us-convert-container
        image: asia-northeast3-docker.pkg.dev/customs-clearance-system/docker-repo/hscode-recommender:latest
        ports:
        - containerPort: 8006
        env:
        - name: PORT
          value: "8006"
        - name: ENVIRONMENT
          value: "production"
        - name: SERVICE_NAME
          value: "US-Korea HS Code Converter Service"
        - name: UV_SYSTEM_PYTHON
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENABLE_DOCS
          value: "true"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        - name: US_TARIFF_FILE
          value: "/app/us_tariff_table_20250714.xlsx"
        command: ["/bin/sh"]
        args: ["-c", "uv run uvicorn src.us_main:app --host 0.0.0.0 --port ${PORT}"]
---
apiVersion: v1
kind: Service
metadata:
  name: hscode-us-convert-service
spec:
  selector:
    app: hscode-us-convert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
  type: LoadBalancer