[build]
builder = "nixpacks"
buildCommand = "uv sync && uv run python -c 'print(\"US Convert service build completed\")'"

[deploy]
startCommand = "uv run uvicorn src.us_main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PORT = "8006"
ENVIRONMENT = "production"

# OpenAI API (필수 - LLM 강화 기능)
OPENAI_API_KEY = { default = "" }

# 서비스 메타데이터
SERVICE_NAME = "US-Korea HS Code Converter Service"
SERVICE_VERSION = "1.0.0"
SERVICE_DESCRIPTION = "미국→한국 HS코드 변환 API 서비스 (LLM 강화)"

# 데이터 파일 경로
US_TARIFF_FILE = "/app/관세청_미국 관세율표_20250714.xlsx"
CACHE_DIR = "/app/cache"
DATA_DIR = "/app/data"

# 로깅 설정
LOG_LEVEL = "INFO"
ENABLE_DOCS = "true"

# uv 환경 설정
UV_SYSTEM_PYTHON = "1"