version: '3.8'

services:
  ai-gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/customs_ai_db
      - REDIS_URL=redis://redis:6379/0
      - SPRING_BOOT_BASE_URL=http://host.docker.internal:8080
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - customs-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=customs_ai_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - customs-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - customs-network

  model-ocr:
    build:
      context: ../models/model-ocr
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_API_KEY=${AZURE_API_KEY}
    restart: unless-stopped
    networks:
      - customs-network

  model-report:
    build:
      context: ../models/model-report
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - customs-network

volumes:
  postgres_data:
  redis_data:

networks:
  customs-network:
    driver: bridge