[project]
name = "chatbot-fastapi"
version = "1.0.0"
description = "Railway 배포용 LangGraph 기반 관세법 전문 챗봇 FastAPI 서비스"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "관세 통관 시스템 개발팀", email = "dev@customs-clearance.com" }
]
keywords = ["fastapi", "langchain", "langgraph", "chatbot", "customs", "rag"]
requires-python = ">=3.11"

# Railway 배포용 최소 의존성 (OCR, PDF, Java 제외)
dependencies = [
    # FastAPI 및 웹 서버
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    
    # 비동기 처리
    "aiofiles>=23.2.1",
    "httpx>=0.25.2",
    
    # 데이터베이스 (PostgreSQL)
    "asyncpg>=0.29.0",
    "sqlalchemy[asyncio]>=2.0.23",
    "alembic>=1.12.1",
    
    # AI/ML 라이브러리 (RAG 챗봇 핵심)
    "openai>=1.3.0",
    "langchain-core>=0.1.0",
    "langchain-openai>=0.0.2",
    "langchain-chroma>=0.1.0",
    "langgraph>=0.0.20",
    "chromadb>=0.4.18",
    
    # 데이터 처리 (최소한)
    "pandas>=2.1.3",
    "numpy>=1.25.2",
    "pyyaml>=6.0.1",
    
    # 환경 설정
    "python-dotenv>=1.0.0",
    
    # 보안 및 인증
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.6",
    
    # 유틸리티
    "typing-extensions>=4.8.0",
    "python-json-logger>=2.0.7",
    
    # 텍스트 처리 (최소한)
    "chardet>=5.2.0",
]

# 선택적 의존성 그룹
[project.optional-dependencies]
# 개발 도구 (로컬 개발용)
dev = [
    "pytest>=7.4.3",
    "pytest-asyncio>=0.21.1",
    "black>=23.11.0",
    "isort>=5.12.0",
    "flake8>=6.1.0",
]

# 프로덕션 도구
production = [
    "gunicorn>=21.2.0",
]

[project.urls]
Homepage = "https://github.com/customs-clearance/chatbot-fastapi"
Repository = "https://github.com/customs-clearance/chatbot-fastapi"

[project.scripts]
start = "main:main"

[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

# Hatch 설정
[tool.hatch.version]
path = "__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["app"]

# 환경별 설정
[tool.hatch.envs.default]
dependencies = [
    "chatbot-fastapi[production]"
]

[tool.hatch.envs.default.scripts]
# Railway 배포용 실행 스크립트
prod = "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1"