[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
startCommand = ""

[env]
# 기본 환경변수들
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
ENVIRONMENT = "production"

# Railway 환경 식별
RAILWAY_ENVIRONMENT = "true"

# PostgreSQL 연결 설정 (Railway 환경변수를 현재 코드 형식으로 매핑)
POSTGRES_HOST = "$PGHOST"
POSTGRES_PORT = "$PGPORT"
POSTGRES_DB = "$PGDATABASE"
POSTGRES_USER = "$PGUSER"
POSTGRES_PASSWORD = "$PGPASSWORD"

# Redis 연결 설정 (Railway 환경변수를 현재 코드 형식으로 매핑)
# Railway Redis 서비스 생성 시 자동으로 제공되는 환경변수들 사용
# REDIS_HOST = "$REDIS_HOST"
# REDIS_PORT = "$REDIS_PORT" 
# REDIS_PASSWORD = "$REDIS_PASSWORD"

# 연결 풀 최적화 (Railway 환경용)
POSTGRES_POOL_SIZE = "3"
POSTGRES_MAX_OVERFLOW = "7"
REDIS_MAX_CONNECTIONS = "8"

# ChromaDB 연결 설정 (Railway ChromaDB 서비스와 연결)
CHROMADB_MODE = "docker"
# CHROMADB_HOST = "your-chromadb-service.railway.app"
# CHROMADB_PORT = "443"
# CHROMADB_USE_SSL = "true"

# OpenAI API 키는 Railway 대시보드에서 설정
# OPENAI_API_KEY = "sk-..."