[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/v1/heartbeat"
healthcheckTimeout = 30
restartPolicyType = "always"
startCommand = ""

[env]
CHROMA_HOST = "0.0.0.0"
CHROMA_LOG_LEVEL = "INFO"
ANONYMIZED_TELEMETRY = "false"
IS_PERSISTENT = "true"
PERSIST_DIRECTORY = "/chroma/chroma"